Public Class Form1

    Dim skin(230) As String

    Sub setvalue()
        skin(0) = "血月舞忍 阿卡莉"
        skin(1) = "魅惑時代 阿璃"
        skin(2) = "菁英學院 阿璃"
        skin(3) = "悲劇騎士 阿姆姆"
        skin(4) = "哀傷機器人 阿姆姆"
        skin(5) = "星際之門 阿祈爾"
        skin(6) = "墳場霸者 阿祈爾"
        skin(7) = "SKT T1 阿祈爾"
        skin(8) = "鳳雛砂皇 龐統"
        skin(9) = "菁英學院 艾克"
        skin(10) = "史前翼禽 艾妮維亞"
        skin(11) = "愛情獵人 艾希"
        skin(12) = "菁英計畫 艾希"
        skin(13) = "安妮夢遊仙境"
        skin(14) = "霜火魔女 安妮"
        skin(15) = "安貝爾與泰妮"
        skin(16) = "功夫熊貓 安妮"
        skin(17) = "中路野獸 玩具安娜"
        skin(18) = "普羅雪精靈 奧莉安娜"
        skin(19) = "刺客舞者 奧莉安娜"
        skin(20) = "甜點精靈 波比"
        skin(21) = "聖潔騎士 波比"
        skin(22) = "綠焰活屍 布蘭德"
        skin(23) = "拳擊機器人 布里茨"
        skin(24) = "i‧布里茨"
        skin(25) = "火箭女孩 崔絲塔娜"
        skin(26) = "諾城霸主 達瑞斯"
        skin(27) = "灌籃高手 達瑞斯"
        skin(28) = "菁英學院 達瑞斯"
        skin(29) = "靈魂收割者 達瑞文"
        skin(30) = "泳池狂歡 達瑞文"
        skin(31) = "闇之女武神 黛安娜"
        skin(32) = "望月女神 黛安娜"
        skin(33) = "弒龍獵人 汎"
        skin(34) = "愛情獵人 汎"
        skin(35) = "SKT T1 汎"
        skin(36) = "破冰殺人鯨 飛斯"
        skin(37) = "火爆警官 菲艾"
        skin(38) = "性感教師 菲歐拉"
        skin(39) = "菁英計畫 菲歐拉"
        skin(40) = "泳池狂歡 菲歐拉"
        skin(41) = "血之魔王 弗拉迪米爾"
        skin(42) = "菁英學院 弗拉迪米爾"
        skin(43) = "符文護衛 弗力貝爾"
        skin(44) = "鋼鐵軍團 蓋倫"
        skin(45) = "海豹突擊隊 剛普朗克"
        skin(46) = "征服者 剛普朗克"
        skin(47) = "海賊船長 剛普朗克"
        skin(48) = "黑道風雲 葛雷夫"
        skin(49) = "泳池狂歡 葛雷夫"
        skin(50) = "聖誕老人 古拉格斯"
        skin(51) = "慕尼黑啤酒節 古拉格斯"
        skin(52) = "黑道風雲 好運姐"
        skin(53) = "彩虹小馬 赫克林"
        skin(54) = "聖誕老人 極靈"
        skin(55) = "遺跡守護者 極靈"
        skin(56) = "好紳士 加里歐"
        skin(57) = "復仇野火 枷蘿"
        skin(58) = "鬼影幢幢 枷蘿"
        skin(59) = "SKT T1 枷蘿"
        skin(60) = "荊棘龍后 枷蘿"
        skin(61) = "聯盟王者 嘉文四世"
        skin(62) = "戰神呂布 嘉文四世"
        skin(63) = "菁英計畫 劫"
        skin(64) = "重武裝 杰西"
        skin(65) = "影焰狼魂 鏡爪"
        skin(66) = "歌劇魅影 卡爾瑟斯"
        skin(67) = "搖滾樂手 卡爾瑟斯"
        skin(68) = "機甲騎士 卡力斯"
        skin(69) = "元祖 卡瑪"
        skin(70) = "征服霸者 卡瑪"
        skin(71) = "虛空魔甲 卡薩丁"
        skin(72) = "深海妖姬 卡莎碧雅"
        skin(73) = "賞金刺客 卡特蓮娜"
        skin(74) = "紅牌 卡特蓮娜"
        skin(75) = "貓女 卡特蓮娜"
        skin(76) = "金戈貝兒 卡特蓮娜"
        skin(77) = "銀白審判 凱爾"
        skin(78) = "蒼穹之翼 凱爾"
        skin(79) = "鎮暴部隊 凱爾"
        skin(80) = "雪嶺突襲 凱能"
        skin(81) = "閃能"
        skin(82) = "荒野保安官 凱特琳"
        skin(83) = "獵頭者 凱特琳"
        skin(84) = "脈衝火焰 凱特琳"
        skin(85) = "史前巨獸 科加斯"
        skin(86) = "血月幽魂 克黎思妲"
        skin(87) = "SKT T1 克黎思妲"
        skin(88) = "侏儸紀 寇格魔"
        skin(89) = "狗格魔"
        skin(90) = "星艦戰將 庫奇"
        skin(91) = "鳳翼天翔 葵恩"
        skin(92) = "北境獵手 葵恩"
        skin(93) = "愛情獵人 葵恩"
        skin(94) = "鋼鐵軍團 拉克絲"
        skin(95) = "元素幻化使 拉克絲"
        skin(96) = "王者庫巴 拉姆斯"
        skin(97) = "重武裝 拉姆斯"
        skin(98) = "叢林機兵 藍寶"
        skin(99) = "社會名流 勒布朗"
        skin(100) = "聖誕詐欺師 勒布朗"
        skin(101) = "闇鴉夜后 勒布朗"
        skin(102) = "獵頭者 雷葛爾"
        skin(103) = "渾沌戰神 雷珂煞"
        skin(104) = "泳池狂歡 雷珂煞"
        skin(105) = "怒火血鱷 雷尼克頓"
        skin(106) = "泳池狂歡 雷尼克頓"
        skin(107) = "樂尼高頓"
        skin(108) = "泳池狂歡 雷歐娜"
        skin(109) = "菁英計畫 雷歐娜"
        skin(110) = "永恆榮耀 雷玟"
        skin(111) = "黎明使者 雷玟"
        skin(112) = "活人禁區 雷茲"
        skin(113) = "海賊重炮手 雷茲"
        skin(114) = "拳霸 李星"
        skin(115) = "泳池狂歡 李星"
        skin(116) = "血之祈舞 麗珊卓"
        skin(117) = "菁英計畫 路西恩"
        skin(118) = "黑貓魔法使 露璐"
        skin(119) = "馴龍高手 露璐"
        skin(120) = "普羅雪精靈 露璐"
        skin(121) = "泳池狂歡 露璐"
        skin(122) = "星光少女組 露璐"
        skin(123) = "霜降使者 馬爾札哈"
        skin(124) = "鬼影幢幢 茂凱"
        skin(125) = "戰爭英雄 茂凱"
        skin(126) = "聖光球 柏茲蒙多"
        skin(127) = "泳池狂歡 蒙多醫生"
        skin(128) = "放逐天使 魔甘娜"
        skin(129) = "凋零薔薇 魔甘娜"
        skin(130) = "戰爭英雄 魔甘娜"
        skin(131) = "釉月倩影 魔甘娜"
        skin(132) = "靈藥魔女 魔甘娜"
        skin(133) = "熔岩巨獸 墨菲特"
        skin(134) = "機甲神盾 墨菲特"
        skin(135) = "白星錦鯉 娜米"
        skin(136) = "阿福之音 娜米"
        skin(137) = "月球漫步 納帝魯斯"
        skin(138) = "星際之門 納瑟斯"
        skin(139) = "雪地靈兔 奈德麗"
        skin(140) = "法國女僕 奈德麗"
        skin(141) = "毛毛仕紳 吶兒"
        skin(142) = "霜降使者 吶兒"
        skin(143) = "探戈靈魂 逆命"
        skin(144) = "異界獵手 逆命"
        skin(145) = "聖誕狂歡 努努"
        skin(146) = "鐵甲雪人 努努"
        skin(147) = "台灣隊長 密使努努"
        skin(148) = "被遺忘者 歐拉夫"
        skin(149) = "哥拉夫"
        skin(150) = "星河黎羽 銳空"
        skin(151) = "惡靈恐懼 瑟雷西"
        skin(152) = "永恆榮耀 瑟雷西"
        skin(153) = "SSW 瑟雷西"
        skin(154) = "星河暮羽 剎雅"
        skin(155) = "黃金甲 慎"
        skin(156) = "武士精神 慎"
        skin(157) = "上路帝王 慎丹利"
        skin(158) = "黑暗騎士 史瓦妮"
        skin(159) = "元祖 史瓦妮"
        skin(160) = "普羅騎士 史瓦妮"
        skin(161) = "海賊參謀 斯溫"
        skin(162) = "強權暴君 斯溫"
        skin(163) = "星空聖女 索拉卡"
        skin(164) = "祈月德拉妮 索拉卡"
        skin(165) = "繆斯女神 索娜"
        skin(166) = "平安夜女神 索娜"
        skin(167) = "龍宮仙女 索娜"
        skin(168) = "電玩女神 索娜"
        skin(169) = "熱音DJ 索娜"
        skin(170) = "金剛芭比 塔里克"
        skin(171) = "SSW 塔隆"
        skin(172) = "魔劍蠻王 泰達米爾"
        skin(173) = "第四棒打擊手 特朗德"
        skin(174) = "元祖 特朗德"
        skin(175) = "約德爾人的一大步"
        skin(176) = "復活兔 提摩"
        skin(177) = "燒肉粽 提摩"
        skin(178) = "萬聖小惡摩 提摩"
        skin(179) = "北風凍原 圖奇"
        skin(180) = "聖堂星靈 威寇茲"
        skin(181) = "白魔導 維迦"
        skin(182) = "完全機械使徒 維克特"
        skin(183) = "重裝狂徒 維克特"
        skin(184) = "百獸戰隊 烏迪爾"
        skin(185) = "極獸霸魂 烏迪爾"
        skin(186) = "全武裝機兵 烏爾加特"
        skin(187) = "神龍聖玉 悟空"
        skin(188) = "泳池狂歡 希格斯"
        skin(189) = "霜降使者 希格斯"
        skin(190) = "鐵龍公主 希瓦娜"
        skin(191) = "煉獄黑火 希瓦娜"
        skin(192) = "霜翼冰龍 希瓦娜"
        skin(193) = "峽谷獵人 希維爾"
        skin(194) = "冰暴裂風 希維爾"
        skin(195) = "戰爭英雄 希維爾"
        skin(196) = "衝浪高手 辛吉德"
        skin(197) = "霜降使者 辛吉德"
        skin(198) = "亞特蘭水巫 星朵拉"
        skin(199) = "黑色猛牛 亞歷斯塔"
        skin(200) = "SKT T1 亞歷斯塔"
        skin(201) = "亞歷哞哞"
        skin(202) = "恐怖鬼屋 夜曲"
        skin(203) = "烈影戰神 夜曲"
        skin(204) = "影之女王 伊芙琳"
        skin(205) = "妙手空空 伊芙琳"
        skin(206) = "致命血蓮 伊莉絲"
        skin(207) = "戰爭英雄 伊莉絲"
        skin(208) = "霜寒劍心 伊瑞莉雅"
        skin(209) = "冰川勇者 伊澤瑞爾"
        skin(210) = "脈衝火焰 伊澤瑞爾"
        skin(211) = "傻笑之王 伊澤逼比"
        skin(212) = "決勝賭豪 伊澤瑞爾"
        skin(213) = "黑桃Ace 伊澤瑞爾"
        skin(214) = "電玩高手 伊澤瑞爾"
        skin(215) = "終極戰士 易大師"
        skin(216) = "菁英計畫 易大師"
        skin(217) = "擺渡人 約瑞科"
        skin(218) = "泥臭臭 札克"
        skin(219) = "泳池狂歡 札克"
        skin(220) = "常山趙子龍 趙信"
        skin(221) = "暴風雨女神 珍娜"
        skin(222) = "海克斯科技 珍娜"
        skin(223) = "霜之女王 珍娜"
        skin(224) = "戰爭英雄 珍娜"
        skin(225) = "氣象主播 珍娜"
        skin(226) = "Fnatic 珍娜"
        skin(227) = "星光少女組 珍娜"
        skin(228) = "劍仙 驚鯢 珍娜"
    End Sub

    Private Sub Form1_Load(sender As System.Object, e As System.EventArgs) Handles MyBase.Load
        setvalue()
        Dim pic(230) As PictureBox
        Dim lab(230) As Label

        Dim t As Integer = 16

        For i = 15 * (t - 1) To 15 * t - 1
            pic(i) = New PictureBox
            With pic(i)
                .Width = 115
                .Height = 65
                .Top = (i Mod 15) * 65
                .Left = 0
                .Image = Image.FromFile("C:\Users\yun\Desktop\lolskin\" + Format(i + 1, "000") + ".bmp")
            End With

            lab(i) = New Label
            With lab(i)
                .AutoSize = True
                .Top = (i Mod 15) * 65 + 18
                .Left = 115
                .Text = skin(i)
                .Font = New Font("新細明體", 20, FontStyle.Bold)
            End With

            Me.Controls.Add(pic(i))
            Me.Controls.Add(lab(i))
        Next
        Me.Top = 0
        Me.Left = 0
    End Sub

    Private Sub Form1_MouseDoubleClick(sender As System.Object, e As System.Windows.Forms.MouseEventArgs) Handles MyBase.MouseDoubleClick
        Me.Close()
    End Sub
End Class
